spring:
  profiles:
    active: dev
  application:
    name: bs_lingxin

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.example.bs_lingxin.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
